language: python

python:
  - "2.7"

install:
  - pip install pytest

script:
  - python hello.py
  - pytest -v -rs hello-test.py

notifications:
  email:
   recipients:
     -test@test.com
  on_success: never
  on_failure: always

